



import React from 'react';
import { useAppContext } from '../../context/AppContext';
import { LogLevel, LogSource } from '../../types';
import DownloadIcon from '../icons/DownloadIcon';
import SendIcon from '../icons/SendIcon';

const LoadingSpinner: React.FC = () => (
    <div className="flex flex-col items-center justify-center h-full gap-4 text-white">
        <svg className="animate-spin h-12 w-12 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        <p className="text-lg font-semibold">Generating image...</p>
        <p className="text-sm">This may take a moment.</p>
    </div>
);

const Placeholder: React.FC = () => (
    <div className="text-center text-slate-400 dark:text-slate-500">
        <svg xmlns="http://www.w3.org/2000/svg" className="mx-auto h-24 w-24" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
        <p className="mt-4 text-xl font-semibold">Your generated image will appear here</p>
    </div>
);

const ImagenDisplay: React.FC = () => {
    const { generatedImage, isImagenLoading, imagenPrompt, sendImageToChat, visionForImagenJson, addLog } = useAppContext();

    const generateFilename = (): string => {
        if (imagenPrompt) {
            const sanitizedPrompt = imagenPrompt
                .toLowerCase()
                .replace(/[^a-z0-9\s-]/g, '')
                .replace(/\s+/g, '-')
                .substring(0, 50);
            return `imagen-${sanitizedPrompt || 'generated'}.png`;
        }
        return `imagen-generated-${Date.now()}.png`;
    };

    const handleDownload = async () => {
        if (!generatedImage) return;
        addLog({ level: LogLevel.INFO, source: LogSource.GENERAL, message: 'User downloading Imagen generated image.' });
        try {
            const response = await fetch(generatedImage);
            const blob = await response.blob();
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = generateFilename();
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
        } catch (error) {
            console.error('Failed to download image:', error);
            addLog({ level: LogLevel.ERROR, source: LogSource.GENERAL, message: 'Failed to download Imagen image.', details: error });
             // Fallback for simple data URLs if fetch fails
            const link = document.createElement('a');
            link.href = generatedImage;
            link.download = generateFilename();
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        }
    };
    
    const handleSendToChat = () => {
        if (!generatedImage) return;
        sendImageToChat({
            imageBase64: generatedImage,
            analysis: visionForImagenJson,
            prompt: imagenPrompt ?? undefined,
        });
    }

    if (isImagenLoading) {
        return <LoadingSpinner />;
    }

    if (!generatedImage) {
        return <Placeholder />;
    }
    
    return (
        <div className="relative w-full h-full group">
            <img src={generatedImage} alt={imagenPrompt || 'Generated by Imagen'} className="object-contain h-full w-full" />
             <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-2">
                 <button
                    onClick={handleSendToChat}
                    className="flex items-center gap-2 px-3 py-1.5 text-sm font-semibold rounded-md transition-colors text-white bg-green-600/80 hover:bg-green-600"
                    aria-label="Send to Chat"
                    title="Send image and analysis to chat"
                >
                    <SendIcon className="w-5 h-5" />
                </button>
                <button
                    onClick={handleDownload}
                    className="flex items-center gap-2 px-3 py-1.5 text-sm font-semibold rounded-md transition-colors text-white bg-black/60 hover:bg-black/80"
                    aria-label="Download generated image"
                    title="Download Image"
                >
                    <DownloadIcon className="w-5 h-5" />
                </button>
            </div>
        </div>
    );
};

export default ImagenDisplay;
