
import React from 'react';
import { ChatMessage as ChatMessageType } from '../../types';
import MarkdownRenderer from '../../utils/markdownRenderer';
import KatjeLogo from '../icons/KatjeLogo';
import { useAppContext } from '../../context/AppContext';
import Accordion from '../ui/Accordion';
import DownloadableImage from '../ui/DownloadableImage';

interface ChatMessageProps {
  message: ChatMessageType;
}

const ImageLoadingSpinner: React.FC = () => (
    <div className="flex items-center justify-center h-32 w-full bg-slate-200 dark:bg-slate-700 rounded-lg mt-2">
        <svg className="animate-spin h-8 w-8 text-primary-light dark:text-primary-dark" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
    </div>
);

const ChatMessage: React.FC<ChatMessageProps> = ({ message }) => {
  const { allEmployees, userName } = useAppContext();
  const isUser = message.role === 'user';
  const isSystem = message.role === 'system';
  const employee = !isUser && !isSystem && message.employeeId ? allEmployees[message.employeeId] : null;

  if (isSystem) {
    return (
        <div className="my-4 mx-auto w-full max-w-md p-3 text-center text-sm text-text-secondary-light dark:text-text-secondary-dark bg-slate-100 dark:bg-slate-800 rounded-lg">
            <p className="font-semibold mb-2">{message.content}</p>
            {message.imageUrl && (
                <div className="mt-2">
                    <DownloadableImage src={message.imageUrl} alt="Shared context" filename="chat-image.png" />
                </div>
            )}
            {message.imageAnalysis && (
                <div className="mt-2 text-left">
                    <Accordion title="View Vision Analysis" startOpen={false}>
                        <pre className="text-xs bg-slate-200 dark:bg-slate-900 p-2 rounded-md overflow-x-auto max-h-60">
                            {JSON.stringify(message.imageAnalysis, null, 2)}
                        </pre>
                    </Accordion>
                </div>
            )}
        </div>
    );
  }

  return (
    <div className={`flex items-start gap-4 my-2 ${isUser ? 'pr-8' : 'pl-2'}`}>
        <div 
            className={`flex-shrink-0 w-10 h-10 rounded-full flex items-center justify-center ${isUser ? 'bg-slate-300 dark:bg-slate-600' : ''}`}
            title={isUser ? (userName || 'You') : (employee ? employee.name : 'System')}
        >
            {isUser ? (
                <span className="text-lg font-bold text-text-primary-light dark:text-text-primary-dark">{(userName || 'U').charAt(0).toUpperCase()}</span>
            ) : employee ? (
                <img src={employee.image} alt={employee.name} className="w-10 h-10 rounded-full object-cover" />
            ) : (
                <KatjeLogo className="w-8 h-8" /> // Fallback for system messages
            )}
        </div>
        <div className={`flex-grow p-4 rounded-xl ${isUser ? 'bg-primary-light/80 dark:bg-primary-dark/80 text-white dark:text-slate-900' : 'bg-surface-light dark:bg-surface-dark'}`}>
            {!isUser && (
                <p className="font-bold mb-1 text-primary-light dark:text-primary-dark">
                    {employee ? employee.name : 'System'}
                </p>
            )}
            <div className={`prose prose-sm max-w-none ${isUser ? 'prose-invert' : 'dark:prose-invert'}`}>
                <MarkdownRenderer content={message.content} />
            </div>
            {message.isGeneratingImage && <ImageLoadingSpinner />}
            {message.imageUrl && !message.isGeneratingImage && (
                 <div className="mt-2 border border-border-light dark:border-border-dark rounded-lg overflow-hidden">
                    <DownloadableImage src={message.imageUrl} alt="Generated by AI" filename="ai-generated-image.png" />
                 </div>
            )}
      </div>
    </div>
  );
};

export default ChatMessage;